Уровень 0:

In [1]:
import numpy as np

In [118]:
# a) 
A = np.array([[-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
AT = A.transpose()
A.dot(AT)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [264]:
# b)
A = np.array([[-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
AT = A.transpose()
A.dot(AT)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [265]:
# c)
A = np.array([[-1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
AT = A.transpose()
A.dot(AT)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [267]:
from numpy import linalg as LA

In [272]:
# d) 
A = np.array([[2, 1], [2, 2]])
LA.det(A)

2.0

In [273]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [277]:
v,w = LA.eig(m)
print(w)
print(v)

[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Уровень 1:

In [ ]:
m = np.array([[1, 2],
              [2,3]])
print(m)

In [283]:
v,w = LA.eigh(m)

In [286]:
D = np.diag(v)

In [291]:
np.dot(np.dot(w.T, D), w)

array([[2., 1.],
       [1., 3.]])